name: Update Screenshots

on:
  push:
  workflow_dispatch:

jobs:

  prepare-pr:
    name: Prepare Screenshots Update PR
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone bevy-website repo
        uses: actions/checkout@master

      - name: Move examples to the correct folder
        run: |
          touch bonjour

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          title: Update Examples Screenshots
          branch-suffix: random
